name: DevOps Microservices CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout Code
      uses: actions/checkout@v3

    - name: ğŸ³ Install hadolint
      run: |
        wget -O ~/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
        chmod +x ~/hadolint

    - name: ğŸ” Lint Dockerfiles (recursive)
      run: |
        find . -name 'Dockerfile' -exec ~/hadolint {} \;

    - name: âˆ Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: ğŸ› ï¸ Lint Helm Chart
      run: helm lint helm-chart

    - name: ğŸ“„ Lint YAML Files
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: .
