name: DevOps Microservices CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout code
      uses: actions/checkout@v3

    - name: ğŸ§¼ Lint Dockerfiles
      uses: hadolint/hadolint-action@v3.1.0

    - name: ğŸ› ï¸ Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: âœ… Lint Helm Charts
      run: helm lint ./helm-chart

    - name: ğŸ” Validate Kubernetes YAML
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: ./kubernetes-manifests
